DROP DATABASE IF EXISTS `restdb`;
DROP USER IF EXISTS `m0tnamk09`@`%`;
CREATE DATABASE IF NOT EXISTS `restdb` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'm0tnamk09'@'%' IDENTIFIED BY '1509';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `restdb`.* TO `m0tnamk09`@`%`;