DROP DATABASE IF EXISTS `step-by-step-masterspring`;
DROP USER IF EXISTS `m0tnamk09`@`%`;
CREATE DATABASE IF NOT EXISTS `step-by-step-masterspring` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'm0tnamk09'@'%' IDENTIFIED BY '1509';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `step-by-step-masterspring`.* TO `m0tnamk09`@`%`;