spring:
  application:
    name: spring-security
  security:
    user:
      name: ${SECURITY_USERNAME:123}
      password: ${SECURITY_PASSWORD:123}

logging:
  level:
    org:
      springframework:
        security: ${SPRING_SECURITY_LOG_LEVEL:TRACE}